import os
import zipfile
import sys
import jsmin
import hashlib

version = sys.argv[1]
if not version:
  print('Please specify the release version as the first argument, e.g. ./publish.py v0.1')
  exit(-1)

z = zipfile.ZipFile(f'{version}.zip', 'w')
hashfile = '''# This file is automatically generated by publish.py
from application_utils import *

'''

def write(filename):
  global hashfile
  if os.path.isdir(filename):
    for f in os.listdir(filename):
      write(filename + '/' + f)
    return

  name, ext = filename.rsplit('.')
  if ext == 'js':
    contents = open(filename).read()
    contents = jsmin.jsmin(contents)
    hash = hashlib.sha256()
    hash.update(contents.encode('utf-8'))
    new_filename = f'{name}-h{hash.hexdigest()[:8]}.{ext}'
    z.writestr(new_filename, contents)

    hashfile += f"host_redirect('{filename}', '/{new_filename}')\n"
  else:
    z.write(filename)

write('application.py')
write('application_database.py')
write('application_utils.py')
write('data')
write('engine')
write('pages')
write('requirements.txt')
z.writestr('application_hashes.py', hashfile)
z.close()

