name: Validate and publish
on:
  workflow_dispatch:
    inputs:
      puzzle:
        required: true
        type: string
      requestId:
        required: true
        type: string

run-name: Validating request ${{ inputs.requestId }}

concurrency:
  group: ${{ github.workflow }} # Limit to one publish action at a time, others will queue behind.

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - run: printenv
    - run: echo "git clone --depth 1 --reference $GITHUB_REF -- https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE"
    - name: Cloning the repo
      run: git clone --depth 1 --reference $GITHUB_REF -- https://github.com/$GITHUB_REPOSITORY $GITHUB_WORKSPACE
    - name: Validating puzzle
      id: validate
      run: python -u .github/workflows/validate.py
      env:
        PUZZLE: ${{ inputs.puzzle }}
        SECRET: ${{ secrets.GPG_KEY }}
    - name: Publishing puzzle ${{ steps.validate.outputs.display_hash }}
      run: |
        git add .
        git config user.email "jbzdarkid@users.noreply.github.com"
        git config user.name "Validate and publish workflow"
        git commit -m "Published puzzle ${{ steps.validate.outputs.display_hash }}"
        # git push
        git show HEAD

