name: Validate and publish
on:
  workflow_dispatch:
    inputs:
      puzzle:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }} # Limit to one publish action at a time, others will queue behind.

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1 # No need for git history
    - name: Validating puzzle
      run: python -u .github/workflows/validate.py
      env:
        PUZZLE: ${{ inputs.puzzle }}
        SECRET: ${{ secrets.GPG_KEY }}
    - name: Publishing puzzle
      run: |
        git add .
        git config user.email "jbzdarkid@users.noreply.github.com"
        git config user.name "Validate and publish workflow"
        git commit -m "Published puzzle ${{ env.display_hash }}"
        # git push
        git show HEAD

